# Don't change this! Version used to track needed updates.
version = 1
noItemSplatterOnDeath = true
noDeathItemDespawn = true
tryItemLavaSaveOnDeath = true
tryItemVoidSaveOnDeath = true
explosionResistantItems = true
noXpSplatterOnDeath = true
playerDropMoreXpOnDeath = true
droppedExperiencePercent = 80
keepArmorOnDeath = false
armorDropList = [  ]
keepHotbarOnDeath = false
hotbarDropList = [  ]
keepOffhandOnDeath = false
offhandDropList = [  ]
keepAccessories = "NONE"
accessoryKeepList = [  ]