#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.atmospheric]
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true

		[types.stone_type.arts_and_crafts]
			white_chalk = true
			gypsum = true
			soapstone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.bountifulfares]
			feldspar = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = false
			jasper = true
			shale = false
			myalite = true
			permafrost = false

		[types.stone_type.darkerdepths]
			aridrock = true
			duskrock = true
			darkslate = true
			grimestone = true

		[types.stone_type.nomansland]
			silt = true

		[types.stone_type.oreganized]
			glance = true

		[types.cake.bountifulfares]
			coconut_cake = true
			cocoa_cake = true
			sponge_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.quark]
			azalea = false
			ancient = false
			blossom = false

		[types.wood_type.bountifulfares]
			hoary = true
			walnut = true

		[types.wood_type.arts_and_crafts]
			cork = true

		[types.wood_type.environmental]
			willow = false
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.nomansland]
			pine = false
			maple = false
			walnut = true
			willow = false

		[types.leaves_type.quark]
			ancient = false
			blue_blossom = false
			lavender_blossom = false
			orange_blossom = false
			yellow_blossom = false
			red_blossom = false

		[types.leaves_type.bountifulfares]
			apple = true
			flowering_apple = true
			orange = true
			flowering_orange = true
			lemon = true
			flowering_lemon = true
			plum = true
			flowering_plum = true
			hoary = true
			walnut = true
			golden_apple = true
			flowering_golden_apple = true

		[types.leaves_type.galosphere]
			opal = true

		[types.leaves_type.arts_and_crafts]
			cork = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = false
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = false
			blue_wisteria = false
			purple_wisteria = false
			white_wisteria = false

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.nomansland]
			yellow_birch = false
			autumnal_oak = false
			pale_cherry = false
			frosted = true
			pine = false
			maple = false
			red_maple = false
			walnut = true
			willow = false
			apple_fruit = false
			pear_fruit = false

#Disables specific entries
[entries]

		[entries.stone_type.create]
			small_brick_wall = true
			cut_wall = true
			small_bricks = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			layered = true
			polished_cut_stairs = true
			cut_brick_wall = true
			pillar = true
			cut_stairs = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = false
			vertical_slab = true

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

		[entries.wood_type.nomansland]
			bookshelf = false
			trimmed_planks = true

		[entries.wood_type.another_furniture]
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.decorative_blocks]
			beam = false
			support = true
			seat = false
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.bountifulfares]
			trellis = true
			pickets = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = false

		[entries.leaves_type.woodworks]
			leaf_pile = true
