// priority: 100

global.WOOD_TYPES = {}
global.DISABLED_WOOD_TYPES = {}
global.ITEM_SWAPPER = new Map()
global.BLOCK_SWAPPER = new Map()
global.ENTITY_SWAPPER = new Map()
global.STRUCTURE_BLOCK_SWAPPER = new Map()
global.STATE_SWAPPER = []
global.BLOCKSWAP_CONFIG = {
    __comment: 'This config was autogenerated from starter_scripts/_core/block_swap.js',
    generate_all_known_states: false,
    retro_gen: false,
    state_swapper: [],
    swapper: new Map()  // becomes an Object after processBlockswapConfig()
}
global.ENTITY_REMOVALS = []
global.REMOVALS = {
    all: new Set(),
    add: function (entry) {
        if (entry != undefined) {
            if (entry instanceof Array) {
                // Filters out undefined elements
                this.all = new Set(this.getAsArray().concat(entry.filter(e => e !== undefined)))
            } else if (entry.constructor === Object) {
                // Add all strings in an object and any nested objects
                this.add(collectStrings(entry))
            } else {
                this.all.add(entry)
            }
        }
    },
    getAsArray: function () { return Array.from(this.all) },
    getBlocks: function () {
        let blockSet = new Set()
        this.all.forEach(entry => {
            if (Item.of(entry).isBlock()) blockSet.add(entry)
        })
        return blockSet
    },
    getItems: function () {
        let itemSet = new Set()
        this.all.forEach(entry => {
            if (!Item.of(entry).isBlock()) itemSet.add(entry)
        })
        return itemSet
    }
}

global.DEBUG_MODE = false

global.COLOURS = [
    'white',
    'orange',
    'magenta',
    'light_blue',
    'yellow',
    'lime',
    'pink',
    'gray',
    'light_gray',
    'cyan',
    'purple',
    'blue',
    'brown',
    'green',
    'red',
    'black'
]

global.readJson = (mod, location, type) => {
    if (type == undefined) return JSON.parse(JsonIO.toString(KJSTweaks.readJsonFromMod(mod, location)))
    else return JSON.parse(JsonIO.toString(KJSTweaks.readJsonFromMod(mod, location, type)))
}

// Collect all strings in a nested object with recursion
function collectStrings(obj) {
    const result = []

    const recurse = (value) => {
        if (typeof value === "string") {
            result.push(value)
        } else if (value && typeof value === "object") {
            for (const key in value) {
                recurse(value[key])
            }
        }
    }

    recurse(obj);
    return result;
}

/**
 * Swap a constructed woodType with another
 * @param {Object} woodTypeFrom - ex: `global.DISABLED_WOOD_TYPES.mod.woodType`
 * @param {Object} woodTypeTo - ex: `global.WOOD_TYPES.mod.woodType`
 */
function swapWoodType(woodTypeFrom, woodTypeTo) {
    Object.keys(woodTypeFrom).forEach(entry => {
        Object.keys(woodTypeFrom[entry]).forEach(woodenBlock => {
            if (woodTypeFrom[entry][woodenBlock] != undefined && woodTypeTo[entry][woodenBlock] != undefined) {
                global.BLOCK_SWAPPER.set(woodTypeFrom[entry][woodenBlock], woodTypeTo[entry][woodenBlock])
            }
        })
    })
}

// maybe in the future I could construct this from the everycomp config
const woodTypesToConstruct = {
    minecraft: {
        oak: true,
        spruce: true,
        birch: true,
        jungle: true,
        dark_oak: true,
        acacia: true,
        mangrove: true,
        bamboo: true,
        cherry: true,
        crimson: true,
        warped: true,
        pale_oak: true,  // vanilla backport's mod id changed
    },
    // quark: {
        // azalea: false,
        // ancient: false,
        // blossom: false,
    // },
    upgrade_aquatic: {
        driftwood: true,
        river: true,
    },
    atmospheric: {
        grimwood: true,
        rosewood: true,
        morado: true,
        yucca: true,
        aspen: false,
        laurel: true,
        kousa: true,
    },
    environmental: {
        willow: false,
        pine: false,
        plum: true,
        wisteria: false,
    },
    endergetic: {
        poise: true,
    },
    autumnity: {
        maple: true,
    },
    // caverns_and_chasms: {
        // azalea: true,
    // },
    natures_spirit: {
        redwood: true,
        sugi: true,
        wisteria: true,
        fir: true,
        willow: true,
        aspen: true,
        maple: false,
        cypress: true,
        olive: true,
        joshua: true,
        ghaf: true,
        palo_verde: true,
        coconut: true,
        cedar: true,
        larch: true,
        mahogany: true,
        saxaul: true,
    },
    // windswept: {
        // holly: true,
        // chestnut: true,
        // pine: true
    // },
    darkerdepths: {
        petrified: true,
    },
    mynethersdelight: {
        powdery: true,
    },
    gardens_of_the_dead: {
        whistlecane: true,
        soulblight: true,
    },
    // collectorsreap: {
        // lucuma: true,
    // },
    // netherexp: {
        // claret: true,
        // smokestalk: true,
    // },
    // goety: {
        // haunted: true,
        // rotten: true,
        // windswept: true,
        // pine: false,
        // chorus: true,
        // corrupt_chorus: true,
    // },
    // cataclysm: {
        // chorus: false,
    // },
    alexscaves: {
        pewen: true,
        thornwood: true,
    },
    malum: {
        runewood: true,
        soulwood: true,
    },
    // unusual_prehistory: {
        // ginkgo: true,
        // lepidodendron: true,
    // },
    // unusualend: {
        // chorus_nest: true,
    // },
}